services:
  - type: web
    name: gifting-shop-backend
    env: node
    plan: free
    private: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: rayd_ent
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CREDITS_UNIT_USD
        value: 0.10
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_PIN
        sync: false
      - key: SELLER_USERNAME
        value: rayd_seller
      - key: CLOUDINARY_URL
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: gifting-shop-webhook-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node stripe-proxy.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PRIVATE_SERVICE_HOST
        value: gifting-shop-backend.internal
      - key: PRIVATE_SERVICE_PORT
        value: 10000
      - key: PRIVATE_SERVICE_PROTOCOL
        value: http
